# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/v2.4.1/configuration-schema.json
package: spec
generate:
  models: true
output: ./api/spec/types.gen.go # relative to root
