version: '3.9'
services:
  go-chi-server:
    container_name: go-chi-server
    image: patilchinmay/go-chi-server:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      target: run
    ports:
      - "8080:8080"
    # env_file: .env
    deploy:
      resources:
        reservations:
          # These are guaranteed to have
          cpus: '0.50' # 50% CPU time of a single core
          memory: 50M # 50 MB Memory
        limits:
          # These are upper limits after which throttling will take place
          cpus: '1'
          memory: 100M
